name: break-sentence
run-name: ${{ github.actor }} is calling Azure BreakSentence API.
on: [push]
jobs:
  setup_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
              python-version: '3.8.10'
      - run: python ./BLEU/breakSentence.py
    