name: break-sentence
run-name: ${{ github.actor }} is calling Azure BreakSentence API.
on: [push]
jobs:
  setup_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
              python-version: '3.10'
      - name: Get-Secrets
        env:
            AZURE_API_KEY1 : ${{ secrets.AZURE_API_KEY1}}
            AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }} 
      - run: pip install requests
      - run: python ./BLEU/breakSentence.py

            
    