name: break-sentence
run-name: ${{ github.actor }} is calling Azure BreakSentence API.
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'source file name '
        default: 'test'
        required: true
        type: string
      type:
        description: 'source file type [.txt|.xlsx]'
        default: '.txt'
        required: true
        type: string
      lang:
        description: 'source file language [en|zh-tw] [EN|ZH-TW]'
        default: 'EN'
        required: true
        type: string

jobs:
  Job-SentenceBreaker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: 
              python-version: '3.10'
      - name: Download packages
        run: pip install requests openpyxl click pandas
      - name: Execuate break-sentence scripts.
        run: python ./BreakSentence/breakSentence.py  --name ${{ inputs.name }} --type ${{ inputs.type }} --lang ${{ inputs.lang }} run
        env:
            AZURE_API_KEY1 : ${{ secrets.AZURE_API_KEY1}}
            AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }} 
      - name: make artifact directory
        run: mkdir -p artifact/
      - name: text file type
        if: ${{ inputs.type  == '.txt' }}
        run:   cp BreakSentence/BreakSentence_Output/Text/${{inputs.name}}${{inputs.type}}  artifact/${{inputs.name}}${{inputs.type}}  
      - name: Excel file type
        if: ${{ inputs.type == '.xlsx'}}
        run:  cp BreakSentence/BreakSentence_Output/Excel/${{inputs.name}}${{inputs.type}}  artifact/${{inputs.name}}${{inputs.type}}    
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
            name: BreakSentence_Results
            path: artifact/${{inputs.name}}${{inputs.type}}       
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
            name: BreakSentence_Results


# on: 
#   push:
#     paths:
#       - 'BreakSentence/BreakSentence_Input/Text/**.txt'
#       - 'BreakSentence/BreakSentence_Input/Excel/**.xlsx'



            
    